package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Attachments generated by hbm2java
 */
@Entity
@Table(name = "attachments")//, schema = "dbo", catalog = "jtrac_test_db")
public class Attachments implements java.io.Serializable {

	private BigDecimal id;
	private Attachments attachments;
	private Items items;
	private String fileName;
	private BigDecimal filePrefix;
	private Set<History> histories = new HashSet<History>(0);
	private Set<Attachments> attachmentses = new HashSet<Attachments>(0);

	public Attachments() {
	}

	public Attachments(BigDecimal id) {
		this.id = id;
	}

	public Attachments(BigDecimal id, Attachments attachments, Items items,
			String fileName, BigDecimal filePrefix, Set<History> histories,
			Set<Attachments> attachmentses) {
		this.id = id;
		this.attachments = attachments;
		this.items = items;
		this.fileName = fileName;
		this.filePrefix = filePrefix;
		this.histories = histories;
		this.attachmentses = attachmentses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "previous_id")
	public Attachments getAttachments() {
		return this.attachments;
	}

	public void setAttachments(Attachments attachments) {
		this.attachments = attachments;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "file_name")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "file_prefix", scale = 0)
	public BigDecimal getFilePrefix() {
		return this.filePrefix;
	}

	public void setFilePrefix(BigDecimal filePrefix) {
		this.filePrefix = filePrefix;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attachments")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "attachments")
	public Set<Attachments> getAttachmentses() {
		return this.attachmentses;
	}

	public void setAttachmentses(Set<Attachments> attachmentses) {
		this.attachmentses = attachmentses;
	}

}
