package za.co.praxis.helpdesk.escalation.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1
import javax.persistence.Table;

/**
 * Config generated by hbm2java
 */
@Entity
@Table(name = "config")//, schema = "dbo", catalog = "jtrac_test_db")
public class Config implements java.io.Serializable {

	private String param;
	private String value;

	public Config() {
	}

	public Config(String param) {
		this.param = param;
	}

	public Config(String param, String value) {
		this.param = param;
		this.value = value;
	}

	@Id
	@Column(name = "param", unique = true, nullable = false)
	public String getParam() {
		return this.param;
	}

	public void setParam(String param) {
		this.param = param;
	}

	@Column(name = "value")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
