package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemItems generated by hbm2java
 */
@Entity
@Table(name = "item_items")//, schema = "dbo", catalog = "jtrac_test_db")
public class ItemItems implements java.io.Serializable {

	private BigDecimal id;
	private Items itemsByRelatedItemId;
	private Items itemsByItemId;
	private Integer type;

	public ItemItems() {
	}

	public ItemItems(BigDecimal id, Items itemsByRelatedItemId,
			Items itemsByItemId) {
		this.id = id;
		this.itemsByRelatedItemId = itemsByRelatedItemId;
		this.itemsByItemId = itemsByItemId;
	}

	public ItemItems(BigDecimal id, Items itemsByRelatedItemId,
			Items itemsByItemId, Integer type) {
		this.id = id;
		this.itemsByRelatedItemId = itemsByRelatedItemId;
		this.itemsByItemId = itemsByItemId;
		this.type = type;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "related_item_id", nullable = false)
	public Items getItemsByRelatedItemId() {
		return this.itemsByRelatedItemId;
	}

	public void setItemsByRelatedItemId(Items itemsByRelatedItemId) {
		this.itemsByRelatedItemId = itemsByRelatedItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id", nullable = false)
	public Items getItemsByItemId() {
		return this.itemsByItemId;
	}

	public void setItemsByItemId(Items itemsByItemId) {
		this.itemsByItemId = itemsByItemId;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
