package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemTags generated by hbm2java
 */
@Entity
@Table(name = "item_tags")//, schema = "dbo", catalog = "jtrac_test_db")
public class ItemTags implements java.io.Serializable {

	private BigDecimal id;
	private Items items;
	private Tags tags;
	private Integer type;

	public ItemTags() {
	}

	public ItemTags(BigDecimal id, Tags tags) {
		this.id = id;
		this.tags = tags;
	}

	public ItemTags(BigDecimal id, Items items, Tags tags, Integer type) {
		this.id = id;
		this.items = items;
		this.tags = tags;
		this.type = type;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tag_id", nullable = false)
	public Tags getTags() {
		return this.tags;
	}

	public void setTags(Tags tags) {
		this.tags = tags;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
