package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name = "items"/*, schema = "dbo", catalog = "jtrac_test_db"*/, uniqueConstraints = @UniqueConstraint(columnNames = {
		"space_id", "sequence_num" }))
public class Items implements java.io.Serializable {

	private BigDecimal id;
	private int version;
	private Users usersByLoggedBy;
	private Users usersByAssignedTo;
	private Items items;
	private ZSpaceSeverityPeriod ZSpaceSeverityPeriod;
	private ZCategories ZCategories;
	private Spaces spaces;
	private BigDecimal sequenceNum;
	private Integer type;
	private Date timeStamp;
	private Date dueDate;
	private Date dateAdded;
	private Double plannedEffort;
	private String summary;
	private Clob detail;
	private String originator;
	private String originatorContact;
	private Integer status;
	private Integer severity;
	private Integer priority;
	private Double cusDbl01;
	private Double cusDbl02;
	private Double cusDbl03;
	private Integer cusInt01;
	private Integer cusInt02;
	private Integer cusInt03;
	private Integer cusInt04;
	private Integer cusInt05;
	private Integer cusInt06;
	private Integer cusInt07;
	private Integer cusInt08;
	private Integer cusInt09;
	private Integer cusInt10;
	private String cusStr01;
	private String cusStr02;
	private String cusStr03;
	private String cusStr04;
	private String cusStr05;
	private Date cusTim01;
	private Date cusTim02;
	private Date cusTim03;
	private Set<ItemTags> itemTagses = new HashSet<ItemTags>(0);
	private Set<ItemItems> itemItemsesForItemId = new HashSet<ItemItems>(0);
	private Set<ZEscalationLogs> ZEscalationLogses = new HashSet<ZEscalationLogs>(
			0);
	private Set<ItemItems> itemItemsesForRelatedItemId = new HashSet<ItemItems>(
			0);
	private Set<History> histories = new HashSet<History>(0);
	private Set<ItemUsers> itemUserses = new HashSet<ItemUsers>(0);
	private Set<Items> itemses = new HashSet<Items>(0);
	private Set<Attachments> attachmentses = new HashSet<Attachments>(0);

	public Items() {
	}

	public Items(BigDecimal id, Users usersByLoggedBy, Spaces spaces,
			BigDecimal sequenceNum) {
		this.id = id;
		this.usersByLoggedBy = usersByLoggedBy;
		this.spaces = spaces;
		this.sequenceNum = sequenceNum;
	}

	public Items(BigDecimal id, Users usersByLoggedBy, Users usersByAssignedTo,
			Items items, ZSpaceSeverityPeriod ZSpaceSeverityPeriod,
			ZCategories ZCategories, Spaces spaces, BigDecimal sequenceNum,
			Integer type, Date timeStamp, Date dueDate, Date dateAdded,
			Double plannedEffort, String summary, Clob detail,
			String originator, String originatorContact, Integer status,
			Integer severity, Integer priority, Double cusDbl01,
			Double cusDbl02, Double cusDbl03, Integer cusInt01,
			Integer cusInt02, Integer cusInt03, Integer cusInt04,
			Integer cusInt05, Integer cusInt06, Integer cusInt07,
			Integer cusInt08, Integer cusInt09, Integer cusInt10,
			String cusStr01, String cusStr02, String cusStr03, String cusStr04,
			String cusStr05, Date cusTim01, Date cusTim02, Date cusTim03,
			Set<ItemTags> itemTagses, Set<ItemItems> itemItemsesForItemId,
			Set<ZEscalationLogs> ZEscalationLogses,
			Set<ItemItems> itemItemsesForRelatedItemId, Set<History> histories,
			Set<ItemUsers> itemUserses, Set<Items> itemses,
			Set<Attachments> attachmentses) {
		this.id = id;
		this.usersByLoggedBy = usersByLoggedBy;
		this.usersByAssignedTo = usersByAssignedTo;
		this.items = items;
		this.ZSpaceSeverityPeriod = ZSpaceSeverityPeriod;
		this.ZCategories = ZCategories;
		this.spaces = spaces;
		this.sequenceNum = sequenceNum;
		this.type = type;
		this.timeStamp = timeStamp;
		this.dueDate = dueDate;
		this.dateAdded = dateAdded;
		this.plannedEffort = plannedEffort;
		this.summary = summary;
		this.detail = detail;
		this.originator = originator;
		this.originatorContact = originatorContact;
		this.status = status;
		this.severity = severity;
		this.priority = priority;
		this.cusDbl01 = cusDbl01;
		this.cusDbl02 = cusDbl02;
		this.cusDbl03 = cusDbl03;
		this.cusInt01 = cusInt01;
		this.cusInt02 = cusInt02;
		this.cusInt03 = cusInt03;
		this.cusInt04 = cusInt04;
		this.cusInt05 = cusInt05;
		this.cusInt06 = cusInt06;
		this.cusInt07 = cusInt07;
		this.cusInt08 = cusInt08;
		this.cusInt09 = cusInt09;
		this.cusInt10 = cusInt10;
		this.cusStr01 = cusStr01;
		this.cusStr02 = cusStr02;
		this.cusStr03 = cusStr03;
		this.cusStr04 = cusStr04;
		this.cusStr05 = cusStr05;
		this.cusTim01 = cusTim01;
		this.cusTim02 = cusTim02;
		this.cusTim03 = cusTim03;
		this.itemTagses = itemTagses;
		this.itemItemsesForItemId = itemItemsesForItemId;
		this.ZEscalationLogses = ZEscalationLogses;
		this.itemItemsesForRelatedItemId = itemItemsesForRelatedItemId;
		this.histories = histories;
		this.itemUserses = itemUserses;
		this.itemses = itemses;
		this.attachmentses = attachmentses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "logged_by", nullable = false)
	public Users getUsersByLoggedBy() {
		return this.usersByLoggedBy;
	}

	public void setUsersByLoggedBy(Users usersByLoggedBy) {
		this.usersByLoggedBy = usersByLoggedBy;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assigned_to")
	public Users getUsersByAssignedTo() {
		return this.usersByAssignedTo;
	}

	public void setUsersByAssignedTo(Users usersByAssignedTo) {
		this.usersByAssignedTo = usersByAssignedTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spaceSeverityPeriod")
	public ZSpaceSeverityPeriod getZSpaceSeverityPeriod() {
		return this.ZSpaceSeverityPeriod;
	}

	public void setZSpaceSeverityPeriod(
			ZSpaceSeverityPeriod ZSpaceSeverityPeriod) {
		this.ZSpaceSeverityPeriod = ZSpaceSeverityPeriod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id")
	public ZCategories getZCategories() {
		return this.ZCategories;
	}

	public void setZCategories(ZCategories ZCategories) {
		this.ZCategories = ZCategories;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "space_id", nullable = false)
	public Spaces getSpaces() {
		return this.spaces;
	}

	public void setSpaces(Spaces spaces) {
		this.spaces = spaces;
	}

	@Column(name = "sequence_num", nullable = false, scale = 0)
	public BigDecimal getSequenceNum() {
		return this.sequenceNum;
	}

	public void setSequenceNum(BigDecimal sequenceNum) {
		this.sequenceNum = sequenceNum;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_stamp", length = 23)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "due_date", length = 23)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", length = 23)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Column(name = "planned_effort", precision = 53, scale = 0)
	public Double getPlannedEffort() {
		return this.plannedEffort;
	}

	public void setPlannedEffort(Double plannedEffort) {
		this.plannedEffort = plannedEffort;
	}

	@Column(name = "summary")
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "detail")
	public Clob getDetail() {
		return this.detail;
	}

	public void setDetail(Clob detail) {
		this.detail = detail;
	}

	@Column(name = "originator", length = 50)
	public String getOriginator() {
		return this.originator;
	}

	public void setOriginator(String originator) {
		this.originator = originator;
	}

	@Column(name = "originator_contact", length = 50)
	public String getOriginatorContact() {
		return this.originatorContact;
	}

	public void setOriginatorContact(String originatorContact) {
		this.originatorContact = originatorContact;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "severity")
	public Integer getSeverity() {
		return this.severity;
	}

	public void setSeverity(Integer severity) {
		this.severity = severity;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "cus_dbl_01", precision = 53, scale = 0)
	public Double getCusDbl01() {
		return this.cusDbl01;
	}

	public void setCusDbl01(Double cusDbl01) {
		this.cusDbl01 = cusDbl01;
	}

	@Column(name = "cus_dbl_02", precision = 53, scale = 0)
	public Double getCusDbl02() {
		return this.cusDbl02;
	}

	public void setCusDbl02(Double cusDbl02) {
		this.cusDbl02 = cusDbl02;
	}

	@Column(name = "cus_dbl_03", precision = 53, scale = 0)
	public Double getCusDbl03() {
		return this.cusDbl03;
	}

	public void setCusDbl03(Double cusDbl03) {
		this.cusDbl03 = cusDbl03;
	}

	@Column(name = "cus_int_01")
	public Integer getCusInt01() {
		return this.cusInt01;
	}

	public void setCusInt01(Integer cusInt01) {
		this.cusInt01 = cusInt01;
	}

	@Column(name = "cus_int_02")
	public Integer getCusInt02() {
		return this.cusInt02;
	}

	public void setCusInt02(Integer cusInt02) {
		this.cusInt02 = cusInt02;
	}

	@Column(name = "cus_int_03")
	public Integer getCusInt03() {
		return this.cusInt03;
	}

	public void setCusInt03(Integer cusInt03) {
		this.cusInt03 = cusInt03;
	}

	@Column(name = "cus_int_04")
	public Integer getCusInt04() {
		return this.cusInt04;
	}

	public void setCusInt04(Integer cusInt04) {
		this.cusInt04 = cusInt04;
	}

	@Column(name = "cus_int_05")
	public Integer getCusInt05() {
		return this.cusInt05;
	}

	public void setCusInt05(Integer cusInt05) {
		this.cusInt05 = cusInt05;
	}

	@Column(name = "cus_int_06")
	public Integer getCusInt06() {
		return this.cusInt06;
	}

	public void setCusInt06(Integer cusInt06) {
		this.cusInt06 = cusInt06;
	}

	@Column(name = "cus_int_07")
	public Integer getCusInt07() {
		return this.cusInt07;
	}

	public void setCusInt07(Integer cusInt07) {
		this.cusInt07 = cusInt07;
	}

	@Column(name = "cus_int_08")
	public Integer getCusInt08() {
		return this.cusInt08;
	}

	public void setCusInt08(Integer cusInt08) {
		this.cusInt08 = cusInt08;
	}

	@Column(name = "cus_int_09")
	public Integer getCusInt09() {
		return this.cusInt09;
	}

	public void setCusInt09(Integer cusInt09) {
		this.cusInt09 = cusInt09;
	}

	@Column(name = "cus_int_10")
	public Integer getCusInt10() {
		return this.cusInt10;
	}

	public void setCusInt10(Integer cusInt10) {
		this.cusInt10 = cusInt10;
	}

	@Column(name = "cus_str_01")
	public String getCusStr01() {
		return this.cusStr01;
	}

	public void setCusStr01(String cusStr01) {
		this.cusStr01 = cusStr01;
	}

	@Column(name = "cus_str_02")
	public String getCusStr02() {
		return this.cusStr02;
	}

	public void setCusStr02(String cusStr02) {
		this.cusStr02 = cusStr02;
	}

	@Column(name = "cus_str_03")
	public String getCusStr03() {
		return this.cusStr03;
	}

	public void setCusStr03(String cusStr03) {
		this.cusStr03 = cusStr03;
	}

	@Column(name = "cus_str_04")
	public String getCusStr04() {
		return this.cusStr04;
	}

	public void setCusStr04(String cusStr04) {
		this.cusStr04 = cusStr04;
	}

	@Column(name = "cus_str_05")
	public String getCusStr05() {
		return this.cusStr05;
	}

	public void setCusStr05(String cusStr05) {
		this.cusStr05 = cusStr05;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cus_tim_01", length = 23)
	public Date getCusTim01() {
		return this.cusTim01;
	}

	public void setCusTim01(Date cusTim01) {
		this.cusTim01 = cusTim01;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cus_tim_02", length = 23)
	public Date getCusTim02() {
		return this.cusTim02;
	}

	public void setCusTim02(Date cusTim02) {
		this.cusTim02 = cusTim02;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cus_tim_03", length = 23)
	public Date getCusTim03() {
		return this.cusTim03;
	}

	public void setCusTim03(Date cusTim03) {
		this.cusTim03 = cusTim03;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<ItemTags> getItemTagses() {
		return this.itemTagses;
	}

	public void setItemTagses(Set<ItemTags> itemTagses) {
		this.itemTagses = itemTagses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemsByItemId")
	public Set<ItemItems> getItemItemsesForItemId() {
		return this.itemItemsesForItemId;
	}

	public void setItemItemsesForItemId(Set<ItemItems> itemItemsesForItemId) {
		this.itemItemsesForItemId = itemItemsesForItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<ZEscalationLogs> getZEscalationLogses() {
		return this.ZEscalationLogses;
	}

	public void setZEscalationLogses(Set<ZEscalationLogs> ZEscalationLogses) {
		this.ZEscalationLogses = ZEscalationLogses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemsByRelatedItemId")
	public Set<ItemItems> getItemItemsesForRelatedItemId() {
		return this.itemItemsesForRelatedItemId;
	}

	public void setItemItemsesForRelatedItemId(
			Set<ItemItems> itemItemsesForRelatedItemId) {
		this.itemItemsesForRelatedItemId = itemItemsesForRelatedItemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<ItemUsers> getItemUserses() {
		return this.itemUserses;
	}

	public void setItemUserses(Set<ItemUsers> itemUserses) {
		this.itemUserses = itemUserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "items")
	public Set<Attachments> getAttachmentses() {
		return this.attachmentses;
	}

	public void setAttachmentses(Set<Attachments> attachmentses) {
		this.attachmentses = attachmentses;
	}

}
