package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LastHistoryRecordPerItemId generated by hbm2java
 */
@Embeddable
public class LastHistoryRecordPerItemId implements java.io.Serializable {

	private BigDecimal id;
	private int version;
	private Integer type;
	private BigDecimal itemId;
	private Double actualEffort;
	private BigDecimal attachmentId;
	private Clob comment;
	private Date timeStamp;
	private BigDecimal loggedBy;
	private BigDecimal assignedTo;
	private String summary;
	private Clob detail;
	private Integer status;
	private BigDecimal reasonOutstandingId;
	private Integer severity;
	private Integer priority;
	private Double cusDbl01;
	private Double cusDbl02;
	private Double cusDbl03;
	private Integer cusInt01;
	private Integer cusInt02;
	private Integer cusInt03;
	private Integer cusInt04;
	private Integer cusInt05;
	private Integer cusInt06;
	private Integer cusInt07;
	private Integer cusInt08;
	private Integer cusInt09;
	private Integer cusInt10;
	private String cusStr01;
	private String cusStr02;
	private String cusStr03;
	private String cusStr04;
	private String cusStr05;
	private Date cusTim01;
	private Date cusTim02;
	private Date cusTim03;
	private Integer spaceSeverityPeriod;

	public LastHistoryRecordPerItemId() {
	}

	public LastHistoryRecordPerItemId(BigDecimal id, int version,
			BigDecimal itemId, BigDecimal loggedBy) {
		this.id = id;
		this.version = version;
		this.itemId = itemId;
		this.loggedBy = loggedBy;
	}

	public LastHistoryRecordPerItemId(BigDecimal id, int version, Integer type,
			BigDecimal itemId, Double actualEffort, BigDecimal attachmentId,
			Clob comment, Date timeStamp, BigDecimal loggedBy,
			BigDecimal assignedTo, String summary, Clob detail, Integer status,
			BigDecimal reasonOutstandingId, Integer severity, Integer priority,
			Double cusDbl01, Double cusDbl02, Double cusDbl03,
			Integer cusInt01, Integer cusInt02, Integer cusInt03,
			Integer cusInt04, Integer cusInt05, Integer cusInt06,
			Integer cusInt07, Integer cusInt08, Integer cusInt09,
			Integer cusInt10, String cusStr01, String cusStr02,
			String cusStr03, String cusStr04, String cusStr05, Date cusTim01,
			Date cusTim02, Date cusTim03, Integer spaceSeverityPeriod) {
		this.id = id;
		this.version = version;
		this.type = type;
		this.itemId = itemId;
		this.actualEffort = actualEffort;
		this.attachmentId = attachmentId;
		this.comment = comment;
		this.timeStamp = timeStamp;
		this.loggedBy = loggedBy;
		this.assignedTo = assignedTo;
		this.summary = summary;
		this.detail = detail;
		this.status = status;
		this.reasonOutstandingId = reasonOutstandingId;
		this.severity = severity;
		this.priority = priority;
		this.cusDbl01 = cusDbl01;
		this.cusDbl02 = cusDbl02;
		this.cusDbl03 = cusDbl03;
		this.cusInt01 = cusInt01;
		this.cusInt02 = cusInt02;
		this.cusInt03 = cusInt03;
		this.cusInt04 = cusInt04;
		this.cusInt05 = cusInt05;
		this.cusInt06 = cusInt06;
		this.cusInt07 = cusInt07;
		this.cusInt08 = cusInt08;
		this.cusInt09 = cusInt09;
		this.cusInt10 = cusInt10;
		this.cusStr01 = cusStr01;
		this.cusStr02 = cusStr02;
		this.cusStr03 = cusStr03;
		this.cusStr04 = cusStr04;
		this.cusStr05 = cusStr05;
		this.cusTim01 = cusTim01;
		this.cusTim02 = cusTim02;
		this.cusTim03 = cusTim03;
		this.spaceSeverityPeriod = spaceSeverityPeriod;
	}

	@Column(name = "id", nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "item_id", nullable = false, scale = 0)
	public BigDecimal getItemId() {
		return this.itemId;
	}

	public void setItemId(BigDecimal itemId) {
		this.itemId = itemId;
	}

	@Column(name = "actual_effort", precision = 53, scale = 0)
	public Double getActualEffort() {
		return this.actualEffort;
	}

	public void setActualEffort(Double actualEffort) {
		this.actualEffort = actualEffort;
	}

	@Column(name = "attachment_id", scale = 0)
	public BigDecimal getAttachmentId() {
		return this.attachmentId;
	}

	public void setAttachmentId(BigDecimal attachmentId) {
		this.attachmentId = attachmentId;
	}

	@Column(name = "comment")
	public Clob getComment() {
		return this.comment;
	}

	public void setComment(Clob comment) {
		this.comment = comment;
	}

	@Column(name = "time_stamp", length = 23)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

	@Column(name = "logged_by", nullable = false, scale = 0)
	public BigDecimal getLoggedBy() {
		return this.loggedBy;
	}

	public void setLoggedBy(BigDecimal loggedBy) {
		this.loggedBy = loggedBy;
	}

	@Column(name = "assigned_to", scale = 0)
	public BigDecimal getAssignedTo() {
		return this.assignedTo;
	}

	public void setAssignedTo(BigDecimal assignedTo) {
		this.assignedTo = assignedTo;
	}

	@Column(name = "summary")
	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Column(name = "detail")
	public Clob getDetail() {
		return this.detail;
	}

	public void setDetail(Clob detail) {
		this.detail = detail;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "reason_outstanding_id", scale = 0)
	public BigDecimal getReasonOutstandingId() {
		return this.reasonOutstandingId;
	}

	public void setReasonOutstandingId(BigDecimal reasonOutstandingId) {
		this.reasonOutstandingId = reasonOutstandingId;
	}

	@Column(name = "severity")
	public Integer getSeverity() {
		return this.severity;
	}

	public void setSeverity(Integer severity) {
		this.severity = severity;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return this.priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	@Column(name = "cus_dbl_01", precision = 53, scale = 0)
	public Double getCusDbl01() {
		return this.cusDbl01;
	}

	public void setCusDbl01(Double cusDbl01) {
		this.cusDbl01 = cusDbl01;
	}

	@Column(name = "cus_dbl_02", precision = 53, scale = 0)
	public Double getCusDbl02() {
		return this.cusDbl02;
	}

	public void setCusDbl02(Double cusDbl02) {
		this.cusDbl02 = cusDbl02;
	}

	@Column(name = "cus_dbl_03", precision = 53, scale = 0)
	public Double getCusDbl03() {
		return this.cusDbl03;
	}

	public void setCusDbl03(Double cusDbl03) {
		this.cusDbl03 = cusDbl03;
	}

	@Column(name = "cus_int_01")
	public Integer getCusInt01() {
		return this.cusInt01;
	}

	public void setCusInt01(Integer cusInt01) {
		this.cusInt01 = cusInt01;
	}

	@Column(name = "cus_int_02")
	public Integer getCusInt02() {
		return this.cusInt02;
	}

	public void setCusInt02(Integer cusInt02) {
		this.cusInt02 = cusInt02;
	}

	@Column(name = "cus_int_03")
	public Integer getCusInt03() {
		return this.cusInt03;
	}

	public void setCusInt03(Integer cusInt03) {
		this.cusInt03 = cusInt03;
	}

	@Column(name = "cus_int_04")
	public Integer getCusInt04() {
		return this.cusInt04;
	}

	public void setCusInt04(Integer cusInt04) {
		this.cusInt04 = cusInt04;
	}

	@Column(name = "cus_int_05")
	public Integer getCusInt05() {
		return this.cusInt05;
	}

	public void setCusInt05(Integer cusInt05) {
		this.cusInt05 = cusInt05;
	}

	@Column(name = "cus_int_06")
	public Integer getCusInt06() {
		return this.cusInt06;
	}

	public void setCusInt06(Integer cusInt06) {
		this.cusInt06 = cusInt06;
	}

	@Column(name = "cus_int_07")
	public Integer getCusInt07() {
		return this.cusInt07;
	}

	public void setCusInt07(Integer cusInt07) {
		this.cusInt07 = cusInt07;
	}

	@Column(name = "cus_int_08")
	public Integer getCusInt08() {
		return this.cusInt08;
	}

	public void setCusInt08(Integer cusInt08) {
		this.cusInt08 = cusInt08;
	}

	@Column(name = "cus_int_09")
	public Integer getCusInt09() {
		return this.cusInt09;
	}

	public void setCusInt09(Integer cusInt09) {
		this.cusInt09 = cusInt09;
	}

	@Column(name = "cus_int_10")
	public Integer getCusInt10() {
		return this.cusInt10;
	}

	public void setCusInt10(Integer cusInt10) {
		this.cusInt10 = cusInt10;
	}

	@Column(name = "cus_str_01")
	public String getCusStr01() {
		return this.cusStr01;
	}

	public void setCusStr01(String cusStr01) {
		this.cusStr01 = cusStr01;
	}

	@Column(name = "cus_str_02")
	public String getCusStr02() {
		return this.cusStr02;
	}

	public void setCusStr02(String cusStr02) {
		this.cusStr02 = cusStr02;
	}

	@Column(name = "cus_str_03")
	public String getCusStr03() {
		return this.cusStr03;
	}

	public void setCusStr03(String cusStr03) {
		this.cusStr03 = cusStr03;
	}

	@Column(name = "cus_str_04")
	public String getCusStr04() {
		return this.cusStr04;
	}

	public void setCusStr04(String cusStr04) {
		this.cusStr04 = cusStr04;
	}

	@Column(name = "cus_str_05")
	public String getCusStr05() {
		return this.cusStr05;
	}

	public void setCusStr05(String cusStr05) {
		this.cusStr05 = cusStr05;
	}

	@Column(name = "cus_tim_01", length = 23)
	public Date getCusTim01() {
		return this.cusTim01;
	}

	public void setCusTim01(Date cusTim01) {
		this.cusTim01 = cusTim01;
	}

	@Column(name = "cus_tim_02", length = 23)
	public Date getCusTim02() {
		return this.cusTim02;
	}

	public void setCusTim02(Date cusTim02) {
		this.cusTim02 = cusTim02;
	}

	@Column(name = "cus_tim_03", length = 23)
	public Date getCusTim03() {
		return this.cusTim03;
	}

	public void setCusTim03(Date cusTim03) {
		this.cusTim03 = cusTim03;
	}

	@Column(name = "spaceSeverityPeriod")
	public Integer getSpaceSeverityPeriod() {
		return this.spaceSeverityPeriod;
	}

	public void setSpaceSeverityPeriod(Integer spaceSeverityPeriod) {
		this.spaceSeverityPeriod = spaceSeverityPeriod;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LastHistoryRecordPerItemId))
			return false;
		LastHistoryRecordPerItemId castOther = (LastHistoryRecordPerItemId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& (this.getVersion() == castOther.getVersion())
				&& ((this.getType() == castOther.getType()) || (this.getType() != null
						&& castOther.getType() != null && this.getType()
						.equals(castOther.getType())))
				&& ((this.getItemId() == castOther.getItemId()) || (this
						.getItemId() != null && castOther.getItemId() != null && this
						.getItemId().equals(castOther.getItemId())))
				&& ((this.getActualEffort() == castOther.getActualEffort()) || (this
						.getActualEffort() != null
						&& castOther.getActualEffort() != null && this
						.getActualEffort().equals(castOther.getActualEffort())))
				&& ((this.getAttachmentId() == castOther.getAttachmentId()) || (this
						.getAttachmentId() != null
						&& castOther.getAttachmentId() != null && this
						.getAttachmentId().equals(castOther.getAttachmentId())))
				&& ((this.getComment() == castOther.getComment()) || (this
						.getComment() != null && castOther.getComment() != null && this
						.getComment().equals(castOther.getComment())))
				&& ((this.getTimeStamp() == castOther.getTimeStamp()) || (this
						.getTimeStamp() != null
						&& castOther.getTimeStamp() != null && this
						.getTimeStamp().equals(castOther.getTimeStamp())))
				&& ((this.getLoggedBy() == castOther.getLoggedBy()) || (this
						.getLoggedBy() != null
						&& castOther.getLoggedBy() != null && this
						.getLoggedBy().equals(castOther.getLoggedBy())))
				&& ((this.getAssignedTo() == castOther.getAssignedTo()) || (this
						.getAssignedTo() != null
						&& castOther.getAssignedTo() != null && this
						.getAssignedTo().equals(castOther.getAssignedTo())))
				&& ((this.getSummary() == castOther.getSummary()) || (this
						.getSummary() != null && castOther.getSummary() != null && this
						.getSummary().equals(castOther.getSummary())))
				&& ((this.getDetail() == castOther.getDetail()) || (this
						.getDetail() != null && castOther.getDetail() != null && this
						.getDetail().equals(castOther.getDetail())))
				&& ((this.getStatus() == castOther.getStatus()) || (this
						.getStatus() != null && castOther.getStatus() != null && this
						.getStatus().equals(castOther.getStatus())))
				&& ((this.getReasonOutstandingId() == castOther
						.getReasonOutstandingId()) || (this
						.getReasonOutstandingId() != null
						&& castOther.getReasonOutstandingId() != null && this
						.getReasonOutstandingId().equals(
								castOther.getReasonOutstandingId())))
				&& ((this.getSeverity() == castOther.getSeverity()) || (this
						.getSeverity() != null
						&& castOther.getSeverity() != null && this
						.getSeverity().equals(castOther.getSeverity())))
				&& ((this.getPriority() == castOther.getPriority()) || (this
						.getPriority() != null
						&& castOther.getPriority() != null && this
						.getPriority().equals(castOther.getPriority())))
				&& ((this.getCusDbl01() == castOther.getCusDbl01()) || (this
						.getCusDbl01() != null
						&& castOther.getCusDbl01() != null && this
						.getCusDbl01().equals(castOther.getCusDbl01())))
				&& ((this.getCusDbl02() == castOther.getCusDbl02()) || (this
						.getCusDbl02() != null
						&& castOther.getCusDbl02() != null && this
						.getCusDbl02().equals(castOther.getCusDbl02())))
				&& ((this.getCusDbl03() == castOther.getCusDbl03()) || (this
						.getCusDbl03() != null
						&& castOther.getCusDbl03() != null && this
						.getCusDbl03().equals(castOther.getCusDbl03())))
				&& ((this.getCusInt01() == castOther.getCusInt01()) || (this
						.getCusInt01() != null
						&& castOther.getCusInt01() != null && this
						.getCusInt01().equals(castOther.getCusInt01())))
				&& ((this.getCusInt02() == castOther.getCusInt02()) || (this
						.getCusInt02() != null
						&& castOther.getCusInt02() != null && this
						.getCusInt02().equals(castOther.getCusInt02())))
				&& ((this.getCusInt03() == castOther.getCusInt03()) || (this
						.getCusInt03() != null
						&& castOther.getCusInt03() != null && this
						.getCusInt03().equals(castOther.getCusInt03())))
				&& ((this.getCusInt04() == castOther.getCusInt04()) || (this
						.getCusInt04() != null
						&& castOther.getCusInt04() != null && this
						.getCusInt04().equals(castOther.getCusInt04())))
				&& ((this.getCusInt05() == castOther.getCusInt05()) || (this
						.getCusInt05() != null
						&& castOther.getCusInt05() != null && this
						.getCusInt05().equals(castOther.getCusInt05())))
				&& ((this.getCusInt06() == castOther.getCusInt06()) || (this
						.getCusInt06() != null
						&& castOther.getCusInt06() != null && this
						.getCusInt06().equals(castOther.getCusInt06())))
				&& ((this.getCusInt07() == castOther.getCusInt07()) || (this
						.getCusInt07() != null
						&& castOther.getCusInt07() != null && this
						.getCusInt07().equals(castOther.getCusInt07())))
				&& ((this.getCusInt08() == castOther.getCusInt08()) || (this
						.getCusInt08() != null
						&& castOther.getCusInt08() != null && this
						.getCusInt08().equals(castOther.getCusInt08())))
				&& ((this.getCusInt09() == castOther.getCusInt09()) || (this
						.getCusInt09() != null
						&& castOther.getCusInt09() != null && this
						.getCusInt09().equals(castOther.getCusInt09())))
				&& ((this.getCusInt10() == castOther.getCusInt10()) || (this
						.getCusInt10() != null
						&& castOther.getCusInt10() != null && this
						.getCusInt10().equals(castOther.getCusInt10())))
				&& ((this.getCusStr01() == castOther.getCusStr01()) || (this
						.getCusStr01() != null
						&& castOther.getCusStr01() != null && this
						.getCusStr01().equals(castOther.getCusStr01())))
				&& ((this.getCusStr02() == castOther.getCusStr02()) || (this
						.getCusStr02() != null
						&& castOther.getCusStr02() != null && this
						.getCusStr02().equals(castOther.getCusStr02())))
				&& ((this.getCusStr03() == castOther.getCusStr03()) || (this
						.getCusStr03() != null
						&& castOther.getCusStr03() != null && this
						.getCusStr03().equals(castOther.getCusStr03())))
				&& ((this.getCusStr04() == castOther.getCusStr04()) || (this
						.getCusStr04() != null
						&& castOther.getCusStr04() != null && this
						.getCusStr04().equals(castOther.getCusStr04())))
				&& ((this.getCusStr05() == castOther.getCusStr05()) || (this
						.getCusStr05() != null
						&& castOther.getCusStr05() != null && this
						.getCusStr05().equals(castOther.getCusStr05())))
				&& ((this.getCusTim01() == castOther.getCusTim01()) || (this
						.getCusTim01() != null
						&& castOther.getCusTim01() != null && this
						.getCusTim01().equals(castOther.getCusTim01())))
				&& ((this.getCusTim02() == castOther.getCusTim02()) || (this
						.getCusTim02() != null
						&& castOther.getCusTim02() != null && this
						.getCusTim02().equals(castOther.getCusTim02())))
				&& ((this.getCusTim03() == castOther.getCusTim03()) || (this
						.getCusTim03() != null
						&& castOther.getCusTim03() != null && this
						.getCusTim03().equals(castOther.getCusTim03())))
				&& ((this.getSpaceSeverityPeriod() == castOther
						.getSpaceSeverityPeriod()) || (this
						.getSpaceSeverityPeriod() != null
						&& castOther.getSpaceSeverityPeriod() != null && this
						.getSpaceSeverityPeriod().equals(
								castOther.getSpaceSeverityPeriod())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + this.getVersion();
		result = 37 * result
				+ (getType() == null ? 0 : this.getType().hashCode());
		result = 37 * result
				+ (getItemId() == null ? 0 : this.getItemId().hashCode());
		result = 37
				* result
				+ (getActualEffort() == null ? 0 : this.getActualEffort()
						.hashCode());
		result = 37
				* result
				+ (getAttachmentId() == null ? 0 : this.getAttachmentId()
						.hashCode());
		result = 37 * result
				+ (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37 * result
				+ (getTimeStamp() == null ? 0 : this.getTimeStamp().hashCode());
		result = 37 * result
				+ (getLoggedBy() == null ? 0 : this.getLoggedBy().hashCode());
		result = 37
				* result
				+ (getAssignedTo() == null ? 0 : this.getAssignedTo()
						.hashCode());
		result = 37 * result
				+ (getSummary() == null ? 0 : this.getSummary().hashCode());
		result = 37 * result
				+ (getDetail() == null ? 0 : this.getDetail().hashCode());
		result = 37 * result
				+ (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37
				* result
				+ (getReasonOutstandingId() == null ? 0 : this
						.getReasonOutstandingId().hashCode());
		result = 37 * result
				+ (getSeverity() == null ? 0 : this.getSeverity().hashCode());
		result = 37 * result
				+ (getPriority() == null ? 0 : this.getPriority().hashCode());
		result = 37 * result
				+ (getCusDbl01() == null ? 0 : this.getCusDbl01().hashCode());
		result = 37 * result
				+ (getCusDbl02() == null ? 0 : this.getCusDbl02().hashCode());
		result = 37 * result
				+ (getCusDbl03() == null ? 0 : this.getCusDbl03().hashCode());
		result = 37 * result
				+ (getCusInt01() == null ? 0 : this.getCusInt01().hashCode());
		result = 37 * result
				+ (getCusInt02() == null ? 0 : this.getCusInt02().hashCode());
		result = 37 * result
				+ (getCusInt03() == null ? 0 : this.getCusInt03().hashCode());
		result = 37 * result
				+ (getCusInt04() == null ? 0 : this.getCusInt04().hashCode());
		result = 37 * result
				+ (getCusInt05() == null ? 0 : this.getCusInt05().hashCode());
		result = 37 * result
				+ (getCusInt06() == null ? 0 : this.getCusInt06().hashCode());
		result = 37 * result
				+ (getCusInt07() == null ? 0 : this.getCusInt07().hashCode());
		result = 37 * result
				+ (getCusInt08() == null ? 0 : this.getCusInt08().hashCode());
		result = 37 * result
				+ (getCusInt09() == null ? 0 : this.getCusInt09().hashCode());
		result = 37 * result
				+ (getCusInt10() == null ? 0 : this.getCusInt10().hashCode());
		result = 37 * result
				+ (getCusStr01() == null ? 0 : this.getCusStr01().hashCode());
		result = 37 * result
				+ (getCusStr02() == null ? 0 : this.getCusStr02().hashCode());
		result = 37 * result
				+ (getCusStr03() == null ? 0 : this.getCusStr03().hashCode());
		result = 37 * result
				+ (getCusStr04() == null ? 0 : this.getCusStr04().hashCode());
		result = 37 * result
				+ (getCusStr05() == null ? 0 : this.getCusStr05().hashCode());
		result = 37 * result
				+ (getCusTim01() == null ? 0 : this.getCusTim01().hashCode());
		result = 37 * result
				+ (getCusTim02() == null ? 0 : this.getCusTim02().hashCode());
		result = 37 * result
				+ (getCusTim03() == null ? 0 : this.getCusTim03().hashCode());
		result = 37
				* result
				+ (getSpaceSeverityPeriod() == null ? 0 : this
						.getSpaceSeverityPeriod().hashCode());
		return result;
	}

}
