package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SpaceSequence generated by hbm2java
 */
@Entity
@Table(name = "space_sequence")//, schema = "dbo", catalog = "jtrac_test_db")
public class SpaceSequence implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal nextSeqNum;

	public SpaceSequence() {
	}

	public SpaceSequence(BigDecimal id) {
		this.id = id;
	}

	public SpaceSequence(BigDecimal id, BigDecimal nextSeqNum) {
		this.id = id;
		this.nextSeqNum = nextSeqNum;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "next_seq_num", scale = 0)
	public BigDecimal getNextSeqNum() {
		return this.nextSeqNum;
	}

	public void setNextSeqNum(BigDecimal nextSeqNum) {
		this.nextSeqNum = nextSeqNum;
	}

}
