package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Spaces generated by hbm2java
 */
@Entity
@Table(name = "spaces"/*, schema = "dbo", catalog = "jtrac_test_db"*/, uniqueConstraints = @UniqueConstraint(columnNames = "prefix_code"))
public class Spaces implements java.io.Serializable {

	private BigDecimal id;
	private int version;
	private Metadata metadata;
	private Integer type;
	private String prefixCode;
	private String name;
	private Clob description;
	private Byte guestAllowed;
	private Set<ZSpaceEmail> ZSpaceEmails = new HashSet<ZSpaceEmail>(0);
	private Set<Items> itemses = new HashSet<Items>(0);
	private Set<UserSpaceRoles> userSpaceRoleses = new HashSet<UserSpaceRoles>(
			0);
	private Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods = new HashSet<ZSpaceSeverityPeriod>(
			0);
	private Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods_1 = new HashSet<ZSpaceSeverityPeriod>(
			0);
	private Set<SpaceUserLevel> spaceUserLevels = new HashSet<SpaceUserLevel>(0);
	private Set<SpaceUserLevel> spaceUserLevels_1 = new HashSet<SpaceUserLevel>(
			0);
	
	private boolean alert_escalate_yn;

	@Column(name = "alert_escalate_yn")
	public boolean isAlert_escalate_yn() {
		return alert_escalate_yn;
	}

	public void setAlert_escalate_yn(boolean alert_escalate_yn) {
		this.alert_escalate_yn = alert_escalate_yn;
	}

	public Spaces() {
	}

	public Spaces(BigDecimal id) {
		this.id = id;
	}

	public Spaces(BigDecimal id, Metadata metadata, Integer type,
			String prefixCode, String name, Clob description,
			Byte guestAllowed, Set<ZSpaceEmail> ZSpaceEmails,
			Set<Items> itemses, Set<UserSpaceRoles> userSpaceRoleses,
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods,
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods_1,
			Set<SpaceUserLevel> spaceUserLevels,
			Set<SpaceUserLevel> spaceUserLevels_1) {
		this.id = id;
		this.metadata = metadata;
		this.type = type;
		this.prefixCode = prefixCode;
		this.name = name;
		this.description = description;
		this.guestAllowed = guestAllowed;
		this.ZSpaceEmails = ZSpaceEmails;
		this.itemses = itemses;
		this.userSpaceRoleses = userSpaceRoleses;
		this.ZSpaceSeverityPeriods = ZSpaceSeverityPeriods;
		this.ZSpaceSeverityPeriods_1 = ZSpaceSeverityPeriods_1;
		this.spaceUserLevels = spaceUserLevels;
		this.spaceUserLevels_1 = spaceUserLevels_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "metadata_id")
	public Metadata getMetadata() {
		return this.metadata;
	}

	public void setMetadata(Metadata metadata) {
		this.metadata = metadata;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "prefix_code", unique = true, length = 10)
	public String getPrefixCode() {
		return this.prefixCode;
	}

	public void setPrefixCode(String prefixCode) {
		this.prefixCode = prefixCode;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	@Column(name = "guest_allowed")
	public Byte getGuestAllowed() {
		return this.guestAllowed;
	}

	public void setGuestAllowed(Byte guestAllowed) {
		this.guestAllowed = guestAllowed;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaces")
	public Set<ZSpaceEmail> getZSpaceEmails() {
		return this.ZSpaceEmails;
	}

	public void setZSpaceEmails(Set<ZSpaceEmail> ZSpaceEmails) {
		this.ZSpaceEmails = ZSpaceEmails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaces")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaces")
	public Set<UserSpaceRoles> getUserSpaceRoleses() {
		return this.userSpaceRoleses;
	}

	public void setUserSpaceRoleses(Set<UserSpaceRoles> userSpaceRoleses) {
		this.userSpaceRoleses = userSpaceRoleses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaces")
	public Set<ZSpaceSeverityPeriod> getZSpaceSeverityPeriods() {
		return this.ZSpaceSeverityPeriods;
	}

	public void setZSpaceSeverityPeriods(
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods) {
		this.ZSpaceSeverityPeriods = ZSpaceSeverityPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaces")
	public Set<ZSpaceSeverityPeriod> getZSpaceSeverityPeriods_1() {
		return this.ZSpaceSeverityPeriods_1;
	}

	public void setZSpaceSeverityPeriods_1(
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods_1) {
		this.ZSpaceSeverityPeriods_1 = ZSpaceSeverityPeriods_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaces")
	public Set<SpaceUserLevel> getSpaceUserLevels() {
		return this.spaceUserLevels;
	}

	public void setSpaceUserLevels(Set<SpaceUserLevel> spaceUserLevels) {
		this.spaceUserLevels = spaceUserLevels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaces")
	public Set<SpaceUserLevel> getSpaceUserLevels_1() {
		return this.spaceUserLevels_1;
	}

	public void setSpaceUserLevels_1(Set<SpaceUserLevel> spaceUserLevels_1) {
		this.spaceUserLevels_1 = spaceUserLevels_1;
	}

}
