package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpaceUserLevel generated by hbm2java
 */
@Entity
@Table(name = "SpaceUserLevel")//, schema = "dbo", catalog = "jtrac_test_db")
public class SpaceUserLevel implements java.io.Serializable {

	private int id;
	private Users users;
	private ZLevels ZLevels;
	private Spaces spaces;

	public SpaceUserLevel() {
	}

	public SpaceUserLevel(int id, Users users, ZLevels ZLevels, Spaces spaces) {
		this.id = id;
		this.users = users;
		this.ZLevels = ZLevels;
		this.spaces = spaces;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "level_id", nullable = false)
	public ZLevels getZLevels() {
		return this.ZLevels;
	}

	public void setZLevels(ZLevels ZLevels) {
		this.ZLevels = ZLevels;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "space_id", nullable = false)
	public Spaces getSpaces() {
		return this.spaces;
	}

	public void setSpaces(Spaces spaces) {
		this.spaces = spaces;
	}

}
