package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ZEscalationLogs generated by hbm2java
 */
@Entity
@Table(name = "z_escalation_logs")//, schema = "dbo", catalog = "jtrac_test_db")
public class ZEscalationLogs implements java.io.Serializable {

	private BigDecimal id;
	private Users usersByAssignedTo;
	private Items items;
	private Users usersByEscalatedTo;
	private Date dueDate;
	private Date timeStamp;

	public ZEscalationLogs() {
	}

	public ZEscalationLogs(BigDecimal id) {
		this.id = id;
	}

	public ZEscalationLogs(BigDecimal id, Users usersByAssignedTo, Items items,
			Users usersByEscalatedTo, Date dueDate, Date timeStamp) {
		this.id = id;
		this.usersByAssignedTo = usersByAssignedTo;
		this.items = items;
		this.usersByEscalatedTo = usersByEscalatedTo;
		this.dueDate = dueDate;
		this.timeStamp = timeStamp;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assigned_to")
	public Users getUsersByAssignedTo() {
		return this.usersByAssignedTo;
	}

	public void setUsersByAssignedTo(Users usersByAssignedTo) {
		this.usersByAssignedTo = usersByAssignedTo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "escalated_to")
	public Users getUsersByEscalatedTo() {
		return this.usersByEscalatedTo;
	}

	public void setUsersByEscalatedTo(Users usersByEscalatedTo) {
		this.usersByEscalatedTo = usersByEscalatedTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "due_date", length = 23)
	public Date getDueDate() {
		return this.dueDate;
	}

	public void setDueDate(Date dueDate) {
		this.dueDate = dueDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_stamp", length = 23)
	public Date getTimeStamp() {
		return this.timeStamp;
	}

	public void setTimeStamp(Date timeStamp) {
		this.timeStamp = timeStamp;
	}

}
