package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZLevels generated by hbm2java
 */
@Entity
@Table(name = "z_levels")//, schema = "dbo", catalog = "jtrac_test_db")
public class ZLevels implements java.io.Serializable {

	private int id;
	private int level;
	private Set<SpaceUserLevel> spaceUserLevels = new HashSet<SpaceUserLevel>(0);
	private Set<SpaceUserLevel> spaceUserLevels_1 = new HashSet<SpaceUserLevel>(
			0);

	public ZLevels() {
	}

	public ZLevels(int id, int level) {
		this.id = id;
		this.level = level;
	}

	public ZLevels(int id, int level, Set<SpaceUserLevel> spaceUserLevels,
			Set<SpaceUserLevel> spaceUserLevels_1) {
		this.id = id;
		this.level = level;
		this.spaceUserLevels = spaceUserLevels;
		this.spaceUserLevels_1 = spaceUserLevels_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "level", nullable = false)
	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZLevels")
	public Set<SpaceUserLevel> getSpaceUserLevels() {
		return this.spaceUserLevels;
	}

	public void setSpaceUserLevels(Set<SpaceUserLevel> spaceUserLevels) {
		this.spaceUserLevels = spaceUserLevels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZLevels")
	public Set<SpaceUserLevel> getSpaceUserLevels_1() {
		return this.spaceUserLevels_1;
	}

	public void setSpaceUserLevels_1(Set<SpaceUserLevel> spaceUserLevels_1) {
		this.spaceUserLevels_1 = spaceUserLevels_1;
	}

}
