package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZSpaceSeverityPeriod generated by hbm2java
 */
@Entity
@Table(name = "z_space_severity_period")//, schema = "dbo", catalog = "jtrac_test_db")
public class ZSpaceSeverityPeriod implements java.io.Serializable {

	private int id;
	private ZSeverities ZSeverities;
	private Spaces spaces;
	private int period;
	private Set<Items> itemses = new HashSet<Items>(0);
	private Set<History> histories = new HashSet<History>(0);

	public ZSpaceSeverityPeriod() {
	}

	public ZSpaceSeverityPeriod(int id, ZSeverities ZSeverities, Spaces spaces,
			int period) {
		this.id = id;
		this.ZSeverities = ZSeverities;
		this.spaces = spaces;
		this.period = period;
	}

	public ZSpaceSeverityPeriod(int id, ZSeverities ZSeverities, Spaces spaces,
			int period, Set<Items> itemses, Set<History> histories) {
		this.id = id;
		this.ZSeverities = ZSeverities;
		this.spaces = spaces;
		this.period = period;
		this.itemses = itemses;
		this.histories = histories;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "severity_id", nullable = false)
	public ZSeverities getZSeverities() {
		return this.ZSeverities;
	}

	public void setZSeverities(ZSeverities ZSeverities) {
		this.ZSeverities = ZSeverities;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "space_id", nullable = false)
	public Spaces getSpaces() {
		return this.spaces;
	}

	public void setSpaces(Spaces spaces) {
		this.spaces = spaces;
	}

	@Column(name = "period", nullable = false)
	public int getPeriod() {
		return this.period;
	}

	public void setPeriod(int period) {
		this.period = period;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZSpaceSeverityPeriod")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZSpaceSeverityPeriod")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

}
