package za.co.praxis.helpdesk.escalation.domain;
// Generated Oct 21, 2013 9:18:53 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ZSpaceEmail generated by hbm2java
 */
@Entity
@Table(name = "z_space_email")//, schema = "dbo", catalog = "jtrac_test_db")
public class ZSpaceEmail implements java.io.Serializable {

	private BigDecimal id;
	private Users users;
	private Spaces spaces;
	private String email;
	private String host;
	private String port;
	private String username;
	private String password;

	public ZSpaceEmail() {
	}

	public ZSpaceEmail(BigDecimal id) {
		this.id = id;
	}

	public ZSpaceEmail(BigDecimal id, Users users, Spaces spaces, String email,
			String host, String port, String username, String password) {
		this.id = id;
		this.users = users;
		this.spaces = spaces;
		this.email = email;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "assign_to")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "space_id")
	public Spaces getSpaces() {
		return this.spaces;
	}

	public void setSpaces(Spaces spaces) {
		this.spaces = spaces;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "host", length = 50)
	public String getHost() {
		return this.host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	@Column(name = "port", length = 5)
	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	@Column(name = "username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
