package za.co.praxis.jtrac.domain;
// Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemUsers generated by hbm2java
 */
@Entity
@Table(name = "item_users")//, schema = "dbo", catalog = "jtrac")
public class ItemUsers implements java.io.Serializable {

	private BigDecimal id;
	private Users users;
	private Items items;
	private Integer type;

	public ItemUsers() {
	}

	public ItemUsers(BigDecimal id, Users users) {
		this.id = id;
		this.users = users;
	}

	public ItemUsers(BigDecimal id, Users users, Items items, Integer type) {
		this.id = id;
		this.users = users;
		this.items = items;
		this.type = type;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "item_id")
	public Items getItems() {
		return this.items;
	}

	public void setItems(Items items) {
		this.items = items;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

}
