package za.co.praxis.jtrac.domain;
// Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * LastHistoryRecordPerItem generated by hbm2java
 */
@Entity
@Table(name = "last_history_record_per_item", schema = "dbo", catalog = "jtrac")
public class LastHistoryRecordPerItem implements java.io.Serializable {

	private LastHistoryRecordPerItemId id;

	public LastHistoryRecordPerItem() {
	}

	public LastHistoryRecordPerItem(LastHistoryRecordPerItemId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, scale = 0)),
			@AttributeOverride(name = "version", column = @Column(name = "version", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type")),
			@AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false, scale = 0)),
			@AttributeOverride(name = "actualEffort", column = @Column(name = "actual_effort", precision = 53, scale = 0)),
			@AttributeOverride(name = "attachmentId", column = @Column(name = "attachment_id", scale = 0)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment")),
			@AttributeOverride(name = "timeStamp", column = @Column(name = "time_stamp", length = 23)),
			@AttributeOverride(name = "loggedBy", column = @Column(name = "logged_by", nullable = false, scale = 0)),
			@AttributeOverride(name = "assignedTo", column = @Column(name = "assigned_to", scale = 0)),
			@AttributeOverride(name = "summary", column = @Column(name = "summary")),
			@AttributeOverride(name = "detail", column = @Column(name = "detail")),
			@AttributeOverride(name = "status", column = @Column(name = "status")),
			@AttributeOverride(name = "severity", column = @Column(name = "severity")),
			@AttributeOverride(name = "priority", column = @Column(name = "priority")),
			@AttributeOverride(name = "cusDbl01", column = @Column(name = "cus_dbl_01", precision = 53, scale = 0)),
			@AttributeOverride(name = "cusDbl02", column = @Column(name = "cus_dbl_02", precision = 53, scale = 0)),
			@AttributeOverride(name = "cusDbl03", column = @Column(name = "cus_dbl_03", precision = 53, scale = 0)),
			@AttributeOverride(name = "cusInt01", column = @Column(name = "cus_int_01")),
			@AttributeOverride(name = "cusInt02", column = @Column(name = "cus_int_02")),
			@AttributeOverride(name = "cusInt03", column = @Column(name = "cus_int_03")),
			@AttributeOverride(name = "cusInt04", column = @Column(name = "cus_int_04")),
			@AttributeOverride(name = "cusInt05", column = @Column(name = "cus_int_05")),
			@AttributeOverride(name = "cusInt06", column = @Column(name = "cus_int_06")),
			@AttributeOverride(name = "cusInt07", column = @Column(name = "cus_int_07")),
			@AttributeOverride(name = "cusInt08", column = @Column(name = "cus_int_08")),
			@AttributeOverride(name = "cusInt09", column = @Column(name = "cus_int_09")),
			@AttributeOverride(name = "cusInt10", column = @Column(name = "cus_int_10")),
			@AttributeOverride(name = "cusStr01", column = @Column(name = "cus_str_01")),
			@AttributeOverride(name = "cusStr02", column = @Column(name = "cus_str_02")),
			@AttributeOverride(name = "cusStr03", column = @Column(name = "cus_str_03")),
			@AttributeOverride(name = "cusStr04", column = @Column(name = "cus_str_04")),
			@AttributeOverride(name = "cusStr05", column = @Column(name = "cus_str_05")),
			@AttributeOverride(name = "cusTim01", column = @Column(name = "cus_tim_01", length = 23)),
			@AttributeOverride(name = "cusTim02", column = @Column(name = "cus_tim_02", length = 23)),
			@AttributeOverride(name = "cusTim03", column = @Column(name = "cus_tim_03", length = 23)),
			@AttributeOverride(name = "spaceSeverityPeriod", column = @Column(name = "spaceSeverityPeriod")),
			@AttributeOverride(name = "reasonOutstandingId", column = @Column(name = "reason_outstanding_id", scale = 0)) })
	public LastHistoryRecordPerItemId getId() {
		return this.id;
	}

	public void setId(LastHistoryRecordPerItemId id) {
		this.id = id;
	}

}
