package za.co.praxis.jtrac.domain;
// Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "tags"/*, schema = "dbo", catalog = "jtrac"*/, uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Tags implements java.io.Serializable {

	private BigDecimal id;
	private Integer type;
	private String name;
	private Clob description;
	private Set<ItemTags> itemTagses = new HashSet<ItemTags>(0);

	public Tags() {
	}

	public Tags(BigDecimal id, String name) {
		this.id = id;
		this.name = name;
	}

	public Tags(BigDecimal id, Integer type, String name, Clob description,
			Set<ItemTags> itemTagses) {
		this.id = id;
		this.type = type;
		this.name = name;
		this.description = description;
		this.itemTagses = itemTagses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public Clob getDescription() {
		return this.description;
	}

	public void setDescription(Clob description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set<ItemTags> getItemTagses() {
		return this.itemTagses;
	}

	public void setItemTagses(Set<ItemTags> itemTagses) {
		this.itemTagses = itemTagses;
	}

}
