package za.co.praxis.jtrac.domain;
// Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZCategories generated by hbm2java
 */
@Entity
@Table(name = "z_categories")//, schema = "dbo", catalog = "jtrac")
public class ZCategories implements java.io.Serializable {

	private BigDecimal id;
	private String description;
	private Set<Items> itemses = new HashSet<Items>(0);

	public ZCategories() {
	}

	public ZCategories(BigDecimal id, String description) {
		this.id = id;
		this.description = description;
	}

	public ZCategories(BigDecimal id, String description, Set<Items> itemses) {
		this.id = id;
		this.description = description;
		this.itemses = itemses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZCategories")
	public Set<Items> getItemses() {
		return this.itemses;
	}

	public void setItemses(Set<Items> itemses) {
		this.itemses = itemses;
	}

}
