package za.co.praxis.jtrac.domain;
// Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZReasonOutstanding generated by hbm2java
 */
@Entity
@Table(name = "z_reason_outstanding")//, schema = "dbo", catalog = "jtrac")
public class ZReasonOutstanding implements java.io.Serializable {

	private BigDecimal id;
	private String description;
	private Set<History> histories = new HashSet<History>(0);

	public ZReasonOutstanding() {
	}

	public ZReasonOutstanding(BigDecimal id) {
		this.id = id;
	}

	public ZReasonOutstanding(BigDecimal id, String description,
			Set<History> histories) {
		this.id = id;
		this.description = description;
		this.histories = histories;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZReasonOutstanding")
	public Set<History> getHistories() {
		return this.histories;
	}

	public void setHistories(Set<History> histories) {
		this.histories = histories;
	}

}
