package za.co.praxis.jtrac.domain;
// Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ZServerSettings generated by hbm2java
 */
@Entity
@Table(name = "z_server_settings")//, schema = "dbo", catalog = "jtrac")
public class ZServerSettings implements java.io.Serializable {

	private long id;
	private String url;

	public ZServerSettings() {
	}

	public ZServerSettings(long id) {
		this.id = id;
	}

	public ZServerSettings(long id, String url) {
		this.id = id;
		this.url = url;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 18, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "url", length = 100)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
