package za.co.praxis.jtrac.domain;
// Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZSeverities generated by hbm2java
 */
@Entity
@Table(name = "z_severities")//, schema = "dbo", catalog = "jtrac")
public class ZSeverities implements java.io.Serializable {

	private int id;
	private String description;
	private Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods = new HashSet<ZSpaceSeverityPeriod>(
			0);
	private Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods_1 = new HashSet<ZSpaceSeverityPeriod>(
			0);

	public ZSeverities() {
	}

	public ZSeverities(int id, String description) {
		this.id = id;
		this.description = description;
	}

	public ZSeverities(int id, String description,
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods,
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods_1) {
		this.id = id;
		this.description = description;
		this.ZSpaceSeverityPeriods = ZSpaceSeverityPeriods;
		this.ZSpaceSeverityPeriods_1 = ZSpaceSeverityPeriods_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZSeverities")
	public Set<ZSpaceSeverityPeriod> getZSpaceSeverityPeriods() {
		return this.ZSpaceSeverityPeriods;
	}

	public void setZSpaceSeverityPeriods(
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods) {
		this.ZSpaceSeverityPeriods = ZSpaceSeverityPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ZSeverities")
	public Set<ZSpaceSeverityPeriod> getZSpaceSeverityPeriods_1() {
		return this.ZSpaceSeverityPeriods_1;
	}

	public void setZSpaceSeverityPeriods_1(
			Set<ZSpaceSeverityPeriod> ZSpaceSeverityPeriods_1) {
		this.ZSpaceSeverityPeriods_1 = ZSpaceSeverityPeriods_1;
	}

}
