package info.jtrac.domain;

//Generated Oct 18, 2013 2:28:49 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
* ZSpaceEmail generated by hbm2java
*/

public class ZSpaceEmail implements Serializable {

	private String email;
	private String host;
	private String port;
	private String username;
	private String password;
	private long id;
	public long getId() {
		return id;
	}

	private Space space;
	private User user;
	

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Space getSpace() {
		return space;
	}

	public void setSpace(Space space) {
		this.space = space;
	}

	public void setId(long id) {
		this.id = id;
	}

	public ZSpaceEmail(String email, String host, String port, String username,
			String password, long id, Space space, User user) {
		super();
		this.email = email;
		this.host = host;
		this.port = port;
		this.username = username;
		this.password = password;
		this.id = id;
		this.space = space;
		this.user = user;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHost() {
		return host;
	}

	public void setHost(String host) {
		this.host = host;
	}

	public String getPort() {
		return port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public ZSpaceEmail() {
	}

	public String getAuthority() {
		// TODO Auto-generated method stub
		return null;
	}

	
}
